version: 0.2

phases: 
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
            - ACCOUNT_ID=778595316650
            - DEFAULT_REGION=eu-central-1
            - echo "Logging in to Amazon ECR..."
            - aws ecr get-login-password --region $DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$DEFAULT_REGION.amazonaws.com
            - IMAGE_REPO_URI=778595316650.dkr.ecr.eu-central-1.amazonaws.com/portfolio
            - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    build:
        commands:
            - echo "build started on `date`"
            - echo "Building the Docker image..."
            - docker build -t $IMAGE_REPO_URI:latest .
            - docker tag $IMAGE_REPO_URI:latest $IMAGE_REPO_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo "Build completed on `date`"
            - echo "Pushing the Docker image..."
            - docker push $IMAGE_REPO_URI:latest
            - docker push $IMAGE_REPO_URI:$IMAGE_TAG
        finally:
            - echo "Docker image pushed to $IMAGE_REPO_URI successfully"
            
